var NumberOfWords = 116
var words = new BuildArray(NumberOfWords)

// Use the following variables to 
// define your random words:
words[1] = "https://shrinkurl.org/OjoJWC" 
words[2] = "https://shrinkurl.org/e2gUJfY" 
words[3] = "https://shrinkurl.org/Nwrc" 
words[4] = "https://shrinkurl.org/qAsUS" 
words[5] = "https://shrinkurl.org/fn5dLO1" 
words[6] = "https://shrinkurl.org/57kmZ" 
words[7] = "https://shrinkurl.org/JKmk5Rl" 
words[8] = "https://shrinkurl.org/VutU" 
words[9] = "https://shrinkurl.org/4quXv" 
words[10] = "https://shrinkurl.org/12StzpJ" 
words[11] = "https://shrinkurl.org/kLlODL" 
words[12] = "https://shrinkurl.org/nh5uc" 
words[13] = "https://shrinkurl.org/58xH6682" 
words[14] = "https://shrinkurl.org/DAdwR" 
words[15] = "https://shrinkurl.org/LGkO" 
words[16] = "https://shrinkurl.org/iPLsX1" 
words[17] = "https://shrinkurl.org/ZsPXbc" 
words[18] = "https://shrinkurl.org/VZN0w8" 
words[19] = "https://shrinkurl.org/iqkfnH" 
words[20] = "https://shrinkurl.org/9dnsEk" 
words[21] = "https://shrinkurl.org/kAxT" 
words[22] = "https://shrinkurl.org/yncH" 
words[23] = "https://shrinkurl.org/d3RByR" 
words[24] = "https://shrinkurl.org/xgrbrc9" 
words[25] = "https://shrinkurl.org/fjeZ88IH" 
words[26] = "https://shrinkurl.org/65u6O2K7" 
words[27] = "https://shrinkurl.org/JwfCUa" 
words[28] = "https://shrinkurl.org/LeExDZpd" 
words[29] = "https://shrinkurl.org/FzMp" 
words[30] = "https://shrinkurl.org/voWR" 
words[31] = "https://shrinkurl.org/jVY76" 
words[32] = "https://shrinkurl.org/uxxRl" 
words[33] = "https://shrinkurl.org/MyjtnKG" 
words[34] = "https://shrinkurl.org/NHdz" 
words[35] = "https://shrinkurl.org/FHDhOPx" 
words[36] = "https://shrinkurl.org/BF2vg" 
words[37] = "https://shrinkurl.org/ZQJZ" 
words[38] = "https://shrinkurl.org/brX6vqu" 
words[39] = "https://shrinkurl.org/lYGP" 
words[40] = "https://shrinkurl.org/1DlO8L" 
words[41] = "https://shrinkurl.org/TKsYec" 
words[42] = "https://shrinkurl.org/IcnpI" 
words[43] = "https://shrinkurl.org/9CK3" 
words[44] = "https://shrinkurl.org/gG5s5N" 
words[45] = "https://shrinkurl.org/8c5HRAq" 
words[46] = "https://shrinkurl.org/kkws7wGx" 
words[47] = "https://shrinkurl.org/sUO5v" 
words[48] = "https://shrinkurl.org/OWNFKJ" 
words[49] = "https://shrinkurl.org/ijI7m" 
words[50] = "https://shrinkurl.org/qFWYULT" 
words[51] = "https://shrinkurl.org/HKJFHG9R" 
words[52] = "https://shrinkurl.org/gx66gpJo" 
words[53] = "https://shrinkurl.org/ncxo" 
words[54] = "https://shrinkurl.org/wX7OUTRJ" 
words[55] = "https://shrinkurl.org/e8M0XJ" 
words[56] = "https://shrinkurl.org/ven2" 
words[57] = "https://shrinkurl.org/JHurv" 
words[58] = "https://shrinkurl.org/Cp3iQxr" 
words[59] = "https://shrinkurl.org/3JAZ" 
words[60] = "https://shrinkurl.org/CSPyIbgF" 
words[61] = "https://shrinkurl.org/ln8o" 
words[62] = "https://shrinkurl.org/ZA6Jt5" 
words[63] = "https://shrinkurl.org/m4rr7TM" 
words[64] = "https://shrinkurl.org/Ulu11" 
words[65] = "https://shrinkurl.org/klD5Am" 
words[66] = "https://shrinkurl.org/WXT7wusR" 
words[67] = "https://shrinkurl.org/jUzID" 
words[68] = "https://shrinkurl.org/c8nN" 
words[69] = "https://shrinkurl.org/O42FZ958" 
words[70] = "https://shrinkurl.org/olRahN" 
words[71] = "https://shrinkurl.org/Yf9xR3Rm" 
words[72] = "https://shrinkurl.org/5ZsJhsd" 
words[73] = "https://shrinkurl.org/zERbdsN4" 
words[74] = "https://shrinkurl.org/0HdQB" 
words[75] = "https://shrinkurl.org/GL1vcT" 
words[76] = "https://shrinkurl.org/0oUkwTKL" 
words[77] = "https://shrinkurl.org/X4iwiZe" 
words[78] = "https://shrinkurl.org/J9ZnYoo" 
words[79] = "https://shrinkurl.org/0hdQ1qzj" 
words[80] = "https://shrinkurl.org/SZPZeV" 
words[81] = "https://shrinkurl.org/yXnOm5T" 
words[82] = "https://shrinkurl.org/1AP8" 
words[83] = "https://shrinkurl.org/tk9ap7zI" 
words[84] = "https://shrinkurl.org/s8dYE" 
words[85] = "https://shrinkurl.org/OSXCpVA" 
words[86] = "https://shrinkurl.org/x5ufTAv8" 
words[87] = "https://shrinkurl.org/sTRsKzAE" 
words[88] = "https://shrinkurl.org/gHPOJ1W" 
words[89] = "https://shrinkurl.org/oijB3h0" 
words[90] = "https://shrinkurl.org/L11oSnOS" 
words[91] = "https://shrinkurl.org/dRTkx" 
words[92] = "https://shrinkurl.org/8xN5a" 
words[93] = "https://shrinkurl.org/a6WKAXs" 
words[94] = "https://shrinkurl.org/xz0S" 
words[95] = "https://shrinkurl.org/VofKJo5f" 
words[96] = "https://shrinkurl.org/Gv0IUyZ1" 
words[97] = "https://shrinkurl.org/zxCpLs" 
words[98] = "https://shrinkurl.org/SBS6cuY" 
words[99] = "https://shrinkurl.org/HSSvXcK" 
words[100] = "https://shrinkurl.org/lZKtQ" 
words[101] = "https://shrinkurl.org/91fqTBPO" 
words[102] = "https://shrinkurl.org/zVuUhU" 
words[103] = "https://shrinkurl.org/qthJNb9" 
words[104] = "https://shrinkurl.org/VoB0g" 
words[105] = "https://shrinkurl.org/lNE5" 
words[106] = "https://shrinkurl.org/0KF5JL" 
words[107] = "https://shrinkurl.org/tbwzy" 
words[108] = "https://shrinkurl.org/dOWaLq2" 
words[109] = "https://shrinkurl.org/QKyb" 
words[110] = "https://shrinkurl.org/gJDHBRCJ" 
words[111] = "https://shrinkurl.org/mL72b8F" 
words[112] = "https://shrinkurl.org/1PDagS" 
words[113] = "https://shrinkurl.org/ClrBkn" 
words[114] = "https://shrinkurl.org/IL4tXBL" 
words[115] = "https://shrinkurl.org/8Dzrr" 
words[116] = "https://shrinkurl.org/stOY3Qf" 

function BuildArray(size){
this.length = size
for (var i = 1; i <= size; i++){
this[i] = null}
return this
}

function PickRandomWord(frm) {
// Generate a random number between 1 and NumberOfWords
var rnd = Math.ceil(Math.random() * NumberOfWords)

// Display the word inside the text box
frm.WordBox.value = words[rnd]
}